ALTER TABLE "invite_codes" ADD COLUMN IF NOT EXISTS "daily_max_uses" integer;
--> statement-breakpoint
ALTER TABLE "invite_codes" ADD COLUMN IF NOT EXISTS "daily_used_count" integer NOT NULL DEFAULT 0;
--> statement-breakpoint
ALTER TABLE "invite_codes" ADD COLUMN IF NOT EXISTS "daily_used_on" varchar(10);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "member_api_shares" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "owner_user_id" integer NOT NULL,
  "recipient_user_id" integer NOT NULL,
  "capability" varchar(16) NOT NULL,
  "max_episodes" integer NOT NULL,
  "used_episodes" integer NOT NULL DEFAULT 0,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "member_api_shares_no_self" CHECK (owner_user_id <> recipient_user_id),
  CONSTRAINT "member_api_shares_capability" CHECK (capability IN ('llm', 'tts')),
  CONSTRAINT "member_api_shares_quota" CHECK (max_episodes > 0 AND used_episodes >= 0)
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "member_api_shares_recipient_idx" ON "member_api_shares" (recipient_user_id, capability, active);
--> statement-breakpoint
ALTER TABLE "member_api_shares" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON "member_api_shares" FROM anon;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON "member_api_shares" FROM authenticated;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'twocast_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON "member_api_shares" TO twocast_app;
    GRANT USAGE, SELECT ON SEQUENCE "member_api_shares_id_seq" TO twocast_app;
    DROP POLICY IF EXISTS "twocast_app_member_api_shares" ON "member_api_shares";
    CREATE POLICY "twocast_app_member_api_shares" ON "member_api_shares"
      FOR ALL TO twocast_app USING (true) WITH CHECK (true);
  END IF;
END $$;
