ALTER TABLE public.invite_sessions ADD COLUMN IF NOT EXISTS login_code_hash varchar(64) UNIQUE;
ALTER TABLE public.invite_sessions ADD COLUMN IF NOT EXISTS display_name varchar(80);
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS folder_path varchar(255) NOT NULL DEFAULT '/';
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS labels json NOT NULL DEFAULT '[]'::json;

CREATE TABLE IF NOT EXISTS public.user_api_settings (
  user_id integer NOT NULL REFERENCES public.invite_sessions(id) ON DELETE CASCADE,
  key varchar(80) NOT NULL,
  encrypted_value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, key)
);
CREATE TABLE IF NOT EXISTS public.api_grants (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES public.invite_sessions(id) ON DELETE CASCADE,
  invite_code_id integer REFERENCES public.invite_codes(id) ON DELETE CASCADE,
  capability varchar(16) NOT NULL CHECK (capability IN ('llm','tts')),
  max_episodes integer NOT NULL CHECK (max_episodes > 0),
  used_episodes integer NOT NULL DEFAULT 0 CHECK (used_episodes >= 0),
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((user_id IS NULL) <> (invite_code_id IS NULL))
);
CREATE INDEX IF NOT EXISTS api_grants_user_idx ON public.api_grants(user_id, capability);
CREATE INDEX IF NOT EXISTS api_grants_invite_idx ON public.api_grants(invite_code_id, capability);
CREATE INDEX IF NOT EXISTS tasks_owner_created_idx ON public.tasks(user_id, created_at DESC);
ALTER TABLE public.user_api_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_grants ENABLE ROW LEVEL SECURITY;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('podcast-files', 'podcast-files', false, 4000000,
  ARRAY['application/pdf','text/plain'])
ON CONFLICT (id) DO NOTHING;
